services:
  mongo:
    build:
      context: .
      dockerfile: Dockerfile.mongo
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: meli
      MONGO_INITDB_ROOT_PASSWORD: secretPassword
    ports:
      - "27017:27017"
    restart: always
  mysql_SuperMarket:
    image: mysql:latest
    container_name: SuperMarket
    environment:
      MYSQL_ROOT_PASSWORD: ultrasecret
      MYSQL_USER: miusuario
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_supermarket:/var/lib/mysql
      - ./databaseSuperMarket.sql:/docker-entrypoint-initdb.d/databaseSuperMarket.sql
    restart: always
  mysql_Bussines:
    image: mysql:latest
    container_name: Bussines
    environment:
      MYSQL_ROOT_PASSWORD: BussinesRoot
      MYSQL_USER: TheBoss
      MYSQL_PASSWORD: BossPassword
    ports:
      - "3307:3306"
    volumes:
      - mysql_data_bussines:/var/lib/mysql
      - ./databaseBussines.sql:/docker-entrypoint-initdb.d/databaseBussines.sql
    restart: always
  app:
    build: .
    container_name: go_app
    depends_on:
      - mongo
      - mysql_SuperMarket
      - mysql_Bussines
    environment:
      MONGO_URI: "mongodb://meli:secretPassword@mongo:27017/"
      MONGO_DATABASE: "test"
      ENCRYPTION_KEY  : "djtGiEcL10b70jsluK0lRA=="
    ports:
      - "8080:8080"
    restart: always

volumes:
  mongo_data:
  mysql_data_supermarket:
  mysql_data_bussines:
